export const geHistoryData = [
  {
    course: 'COMM 110 - Interpersonal Communication',
    units: 3,
    term: 'Spring 2016',
    grade: 'B',
    designation: 'A1 - Oral Communication',
    status: 'Complete',
    additionalReq: null,
  },
  {
    course: 'ENGL 100 - Composition II',
    units: 3,
    term: 'Fall 2015',
    grade: 'A',
    designation: 'A2 - Written Communication',
    status: 'Complete',
    additionalReq: null,
  },
  {
    course: 'waived',
    units: 'waived',
    term: 'waived',
    grade: 'waived',
    designation: 'A3 - Critical Thinking',
    status: 'Complete',
    additionalReq: null,
  },
  {
    course: 'PHYS 151 - Mechanics and Heat',
    units: 3,
    term: 'Fall 2016',
    grade: 'C',
    designation: 'B1 - Physical Science',
    status: 'Complete',
    additionalReq: null,
  },
  {
    course: 'BIOL 200 - General Biology',
    units: 4,
    term: 'Fall 2020',
    grade: null,
    designation: 'B2 - Life Science',
    status: 'In-Progress',
    additionalReq: null,
  },
  {
    course: 'BIOL 200 - General Biology Lab',
    units: 0,
    term: 'Fall 2020',
    grade: null,
    designation: 'B3 - Laboratory Experience',
    status: 'In-Progress',
    additionalReq: null,
  },
  {
    course: 'MATH 119A - Survey of Calculus I',
    units: 3,
    term: 'Fall 2015',
    grade: 'A',
    designation: 'B4 - Mathematics/Quantitative Reasoning',
    status: 'Complete',
    additionalReq: null,
  },
  {
    course: 'LING 151 - Fundamentals of Amer Sign Lang',
    units: 3,
    term: 'Fall 2015',
    grade: 'A',
    designation: 'C2 - Humanities',
    status: 'Complete',
    additionalReq: null,
  },
  {
    course: 'ENGL 100 - Composition II',
    units: 3,
    term: 'Fall 2015',
    grade: 'A',
    designation: 'C3 - Arts / Humanities',
    status: 'Complete',
    additionalReq: null,
  },
  {
    course: 'POSC 100 - Intro American Government',
    units: 3,
    term: 'Fall 2016',
    grade: 'B',
    designation: 'D2 - Constitution and American Ideals',
    status: 'Complete',
    additionalReq: null,
  },
  {
    course: 'ANTH 120 - Intro to Cultural Anthropology',
    units: 3,
    term: 'Fall 2017',
    grade: 'C',
    designation: 'D3 - Social Sciences and Citizenship',
    status: 'Complete',
    additionalReq: 'Global Issues',
  },
  {
    course: 'CECS 105 - Introduction to CECS',
    units: 1,
    term: 'Spring 2016',
    grade: 'B',
    designation: 'E - Lifelong Learning & Self Development',
    status: 'Complete',
    additionalReq: null,
  },
  {
    course: 'ENGR  101 - Intro to Engineering Profession',
    units: 1,
    term: 'Spring 2016',
    grade: 'B',
    designation: 'E - Lifelong Learning & Self Development',
    status: 'Complete',
    additionalReq: null,
  },
  {
    course: 'CECS  491A - Computer Science Senior Project I',
    units: 3,
    term: 'Fall 2020',
    grade: null,
    designation: 'F - Capstone',
    status: 'In-Progress',
    additionalReq: null,
  },
];
