export const majorReqData = [
  {
    course: 'CECS 100',
    title: 'Critical Thinking in the Digital Information Age',
    units: 3,
    designation: 'Lower Div',
  },
  {
    course: 'CECS 105',
    title: 'Introduction to Computer Engineering and Computer Science',
    units: 1,
    designation: 'Lower Div',
  },
  {
    course: 'CECS 174',
    title: 'Introduction to Programming and Problem Solving',
    units: 3,
    designation: 'Lower Div',
  },
  {
    course: 'CECS 225',
    title: 'Digital Logic and Assembly Programming',
    units: 3,
    designation: 'Lower Div',
  },
  {
    course: 'CECS 228',
    title: 'Discrete Structures with Computing Applications',
    units: 3,
    designation: 'Lower Div',
  },
  {
    course: 'CECS 229',
    title: 'Discrete Structures with Computing Applications II',
    units: 3,
    designation: 'Lower Div',
  },
  {
    course: 'CECS 274',
    title: 'Data Structures',
    units: 3,
    designation: 'Lower Div',
  },
  {
    course: 'CECS 277',
    title: 'Object Oriented Application Development',
    units: 3,
    designation: 'Lower Div',
  },
  {
    course: 'CECS 282',
    title: 'Advanced C++',
    units: 3,
    designation: 'Lower Div',
  },
  {
    course: 'ENGR 101',
    title: 'Introduction to the Engineering Profession',
    units: 1,
    designation: 'Lower Div',
  },
  {
    course: 'ENGR 102',
    title: 'Academic Success Skills',
    units: 1,
    designation: 'Lower Div',
  },
  {
    course: 'MATH 122',
    title: 'Calculus I',
    units: 4,
    designation: 'Lower Div',
  },
  {
    course: 'MATH 123',
    title: 'Calculus II',
    units: 4,
    designation: 'Lower Div',
  },
  {
    course: 'PHYS 151',
    title: 'Mechanics and Heat',
    units: 4,
    designation: 'Physical Science',
  },
  {
    course: 'CHEM 111A',
    title: 'General Chemistry',
    units: 5,
    designation: 'Physical Science',
  },
  {
    course: 'BIOL 153',
    title: 'Introduction to Marine Biology',
    units: 3,
    designation: 'Life Science',
  },
  {
    course: 'BIOL 200',
    title: 'General Biology',
    units: 4,
    designation: 'Life Science',
  },
  {
    course: 'BIOL 205',
    title: 'Human Biology',
    units: 4,
    designation: 'Life Science',
  },
  {
    course: 'BIOL 207',
    title: 'Human Physiology',
    units: 4,
    designation: 'Life Science',
  },
  {
    course: 'CECS 323',
    title: 'Database Fundamentals',
    units: 3,
    designation: 'Upper Div',
  },
  {
    course: 'CECS 326',
    title: 'Operating Systems',
    units: 3,
    designation: 'Upper Div',
  },
  {
    course: 'CECS 327',
    title: 'Introduction to Networks and Distributed Computing',
    units: 3,
    designation: 'Upper Div',
  },
  {
    course: 'CECS 328',
    title: 'Algorithms',
    units: 3,
    designation: 'Upper Div',
  },
  {
    course: 'CECS 329',
    title: 'Concepts of Computer Science Theory',
    units: 3,
    designation: 'Upper Div',
  },
  {
    course: 'CECS 341',
    title: 'Computer Architecture and Organization',
    units: 3,
    designation: 'Upper Div',
  },
  {
    course: 'CECS 342',
    title: 'Principles of Programming Languages',
    units: 3,
    designation: 'Upper Div',
  },
  {
    course: 'CECS 343',
    title: 'Introduction to Software Engineering',
    units: 3,
    designation: 'Upper Div',
  },
  {
    course: 'CECS 378',
    title: 'Introduction to Computer Security Principles',
    units: 3,
    designation: 'Upper Div',
  },
  {
    course: 'EE 381',
    title: 'Probability and Statistics with Applications to Computing',
    units: 3,
    designation: 'Upper Div',
  },
  {
    course: 'ENGR 350',
    title: 'Computers, Ethics and Society',
    units: 3,
    designation: 'Upper Div',
  },
  {
    course: 'CECS 491A',
    title: 'Computer Science Senior Project I',
    units: 3,
    designation: 'Upper Div',
  },
  {
    course: 'CECS 491B',
    title: 'Computer Science Senior Project II',
    units: 3,
    designation: 'Upper Div',
  },
  {
    course: 'ENGR 361',
    title: 'Scientific Research Communication',
    units: 3,
    designation: 'Writing Intensive',
  },
  {
    course: 'ENGR 390',
    title: 'Information and Communication Technology for Sustainability',
    units: 3,
    designation: 'Writing Intensive',
  },
  {
    course: 'MATH 323',
    title: 'Introduction to Numerical Analysis',
    units: 4,
    designation: 'Core Elective',
  },
  {
    course: 'CECS 419',
    title: 'Theory of Computation',
    units: 3,
    designation: 'Core Elective',
  },
  {
    course: 'CECS 428',
    title: 'Analysis of Algorithms',
    units: 3,
    designation: 'Core Elective',
  },
  {
    course: 'CECS 429',
    title: 'Search Engine Technology',
    units: 3,
    designation: 'Core Elective',
  },
  {
    course: 'CECS 444',
    title: 'Compiler Construction',
    units: 3,
    designation: 'Core Elective',
  },
  {
    course: 'CECS 445',
    title: 'Software Design and Architecture',
    units: 3,
    designation: 'Core Elective',
  },
  {
    course: 'CECS 448',
    title: 'User Interface Design',
    units: 3,
    designation: 'Core Elective',
  },
  {
    course: 'CECS 449',
    title: 'Computer Graphics',
    units: 3,
    designation: 'Core Elective',
  },
  {
    course: 'CECS 451',
    title: 'Artificial Intelligence',
    units: 3,
    designation: 'Core Elective',
  },
  {
    course: 'CECS 455',
    title: 'Introduction to Game Programming',
    units: 3,
    designation: 'Core Elective',
  },
  {
    course: 'CECS 456',
    title: 'Machine Learning',
    units: 3,
    designation: 'Core Elective',
  },
  {
    course: 'CECS 474',
    title: 'Computer Network Interoperability',
    units: 3,
    designation: 'Core Elective',
  },
  {
    course: 'CECS 478',
    title: 'Introduction to Computer Security',
    units: 3,
    designation: 'Core Elective',
  },
  {
    course: 'CECS 495',
    title: 'Computational Physiology',
    units: 3,
    designation: 'Core Elective',
  },
  {
    course: 'CECS 497',
    title: 'Directed Studies',
    units: '1-3',
    designation: 'Core Elective',
  },
  {
    course: 'CECS 303',
    title: 'Networks and Network Security',
    units: 3,
    designation: 'Applied Elective',
  },
  {
    course: 'CECS 450',
    title: 'Data Visualization',
    units: 3,
    designation: 'Applied Elective',
  },
  {
    course: 'CECS 453',
    title: 'Mobile Application Development',
    units: 3,
    designation: 'Applied Elective',
  },
  {
    course: 'CECS 461',
    title: 'Hardware/Software Co-design',
    units: 3,
    designation: 'Applied Elective',
  },
  {
    course: 'CECS 470',
    title: 'Web Programming and Accessibility',
    units: 3,
    designation: 'Applied Elective',
  },
  {
    course: 'CECS 475',
    title: 'Software Development with Frameworks',
    units: 3,
    designation: 'Applied Elective',
  },
  {
    course: 'CECS 476',
    title: 'System and Network Administration',
    units: 3,
    designation: 'Applied Elective',
  },
];

export const majorReqCategory = [
  'Lower Div',
  'Upper Div',
  'Physical Science',
  'Life Science',
  'Writing Intensive',
  'Core Elective',
  'Applied Elective',
];
