export const geReqData = [
  {
    course: 'Oral Communication',
    units: 3,
    designation: 'A1',
    category: 'A',
  },
  {
    course: 'Written Communication',
    units: 3,
    designation: 'A2',
    category: 'A',
  },
  {
    course: 'Critical Thinking',
    units: 3,
    designation: 'A3',
    category: 'A',
  },
  {
    course: 'Physical Science',
    units: '4-5',
    designation: 'B1',
    category: 'B',
  },
  {
    course: 'Life Science',
    units: '3-4',
    designation: 'B2',
    category: 'B',
  },
  {
    course: 'Laboratory Experience',
    units: 0,
    designation: 'B3',
    category: 'B',
  },
  {
    course: 'Mathematics/Quantitative Reasoning',
    units: 3,
    designation: 'B4',
    category: 'B',
  },
  {
    course: 'Arts',
    units: 3,
    designation: 'C1',
    category: 'C',
  },
  {
    course: 'Humanities',
    units: 3,
    designation: 'C2',
    category: 'C',
  },
  {
    course: 'Arts / Humanities',
    units: 3,
    designation: 'C3',
    category: 'C',
  },
  {
    course: 'US History',
    units: 3,
    designation: 'D1',
    category: 'D',
  },
  {
    course: 'Constitution and American Ideals',
    units: 3,
    designation: 'D2',
    category: 'D',
  },
  {
    course: 'Social Sciences and Citizenship',
    units: 3,
    designation: 'D3',
    category: 'D',
  },
  {
    course: 'E',
    units: 1,
    designation: 'E',
    category: 'E',
  },
  {
    course: 'F',
    units: 3,
    designation: 'F',
    category: 'E',
  },
  {
    course: 'Global Issues',
    units: 3,
    designation: 'Global Issues',
    category: 'Additional Req',
  },
  {
    course: 'Human Diversity',
    units: 3,
    designation: 'Human Diversity',
    category: 'Additional Req',
  },
];
