export const majorHistoryData = [
  {
    course: 'CECS 100 - Critical Thinking in the Digital Information Age',
    units: 3,
    designation: 'Lower Div',
    term: 'Spring 2016',
    grade: 'B',
    status: 'Complete',
  },
  {
    course:
      'CECS 105 - Introduction to Computer Engineering and Computer Science',
    units: 1,
    designation: 'Lower Div',
    term: 'Spring 2016',
    grade: 'B',
    status: 'Complete',
  },
  {
    course: 'CECS 174 - Introduction to Programming and Problem Solving',
    units: 3,
    designation: 'Lower Div',
    term: 'Spring 2016',
    grade: 'B',
    status: 'Complete',
  },
  {
    course: 'CECS 225 - Digital Logic and Assembly Programming',
    units: 3,
    designation: 'Lower Div',
    term: 'Spring 2016',
    grade: 'B',
    status: 'Complete',
  },
  {
    course: 'CECS 228 - Discrete Structures with Computing Applications',
    units: 3,
    designation: 'Lower Div',
    term: 'Spring 2016',
    grade: 'B',
    status: 'Complete',
  },
  {
    course: 'CECS 229 - Discrete Structures with Computing Applications II',
    units: 3,
    designation: 'Lower Div',
    term: 'Spring 2016',
    grade: 'B',
    status: 'Complete',
  },
  {
    course: 'CECS 274 - Data Structures',
    units: 3,
    designation: 'Lower Div',
    term: 'Spring 2016',
    grade: 'B',
    status: 'Complete',
  },
  {
    course: 'CECS 277 - Object Oriented Application Development',
    units: 3,
    designation: 'Lower Div',
    term: 'Spring 2016',
    grade: 'B',
    status: 'Complete',
  },
  {
    course: 'CECS 282 - Advanced C++',
    units: 3,
    designation: 'Lower Div',
    term: 'Spring 2016',
    grade: 'B',
    status: 'Complete',
  },
  {
    course: 'ENGR 101 - Introduction to the Engineering Profession',
    units: 1,
    designation: 'Lower Div',
    term: 'Spring 2016',
    grade: 'B',
    status: 'Complete',
  },
  {
    course: 'MATH 122 - Calculus I',
    units: 4,
    designation: 'Lower Div',
    term: 'Spring 2016',
    grade: 'B',
    status: 'Complete',
  },
  {
    course: 'MATH 123 - Calculus II',
    units: 4,
    designation: 'Lower Div',
    term: 'Spring 2016',
    grade: 'B',
    status: 'Complete',
  },
  {
    course: 'PHYS 151 - Mechanics and Heat',
    units: 4,
    designation: 'Physical Science',
    term: 'Spring 2016',
    grade: 'B',
    status: 'Complete',
  },
  {
    course: 'BIOL 200 - General Biology',
    units: 4,
    designation: 'Life Science',
    term: 'Spring 2016',
    grade: 'B',
    status: 'Complete',
  },
  {
    course: 'CECS 323 - Database Fundamentals',
    units: 3,
    designation: 'Upper Div',
    term: 'Spring 2016',
    grade: 'B',
    status: 'Complete',
  },
  {
    course: 'CECS 326 - Operating Systems',
    units: 3,
    designation: 'Upper Div',
    term: 'Spring 2016',
    grade: 'B',
    status: 'Complete',
  },
  {
    course: 'CECS 328 - Algorithms',
    units: 3,
    designation: 'Upper Div',
    term: 'Spring 2016',
    grade: 'B',
    status: 'Complete',
  },
  {
    course: 'CECS 341 - Computer Architecture and Organization',
    units: 3,
    designation: 'Upper Div',
    term: 'Spring 2016',
    grade: 'B',
    status: 'Complete',
  },
  {
    course: 'CECS 343 - Introduction to Software Engineering',
    units: 3,
    designation: 'Upper Div',
    term: 'Spring 2016',
    grade: 'B',
    status: 'Complete',
  },
  {
    course: 'ENGR 350 - Computers, Ethics and Society',
    units: 3,
    designation: 'Upper Div',
    term: 'Spring 2016',
    grade: 'B',
    status: 'Complete',
  },
  {
    course: 'CECS 491A - Computer Science Senior Project I',
    units: 3,
    designation: 'Upper Div',
    term: 'Spring 2016',
    grade: 'B',
    status: 'Complete',
  },
  {
    course: 'CECS 474 - Computer Network Interoperability',
    units: 3,
    designation: 'Core Elective',
    term: 'Spring 2016',
    grade: 'B',
    status: 'Complete',
  },
  {
    course: 'CECS 476 - System and Network Administration',
    units: 3,
    designation: 'Applied Elective',
    term: 'Spring 2016',
    grade: 'B',
  },
];
